<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>com.example</groupId>
        <artifactId>jee-liberty-posts</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>

    <modelVersion>4.0.0</modelVersion>
    <artifactId>jee-liberty-posts-ear</artifactId>
    <packaging>ear</packaging>

    <dependencies>
        <!-- WAR -->
        <dependency>
            <groupId>com.example</groupId>
            <artifactId>jee-liberty-posts-war</artifactId>
            <version>${project.version}</version>
            <type>war</type>
        </dependency>
        <!-- EJB -->
        <dependency>
            <groupId>com.example</groupId>
            <artifactId>jee-liberty-posts-ejb</artifactId>
            <version>${project.version}</version>
            <type>ejb</type>
        </dependency>
        <!-- JPA -->
        <dependency>
            <groupId>com.example</groupId>
            <artifactId>jee-liberty-posts-jpa</artifactId>
            <version>${project.version}</version>
        </dependency>
    </dependencies>
</project>
